// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/raphoester/ddd-library/internal/contexts/authentication/infrastructure/adapters/inmemory_tokens_storage"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/infrastructure/adapters/inmemory_users_storage"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/infrastructure/controller"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/usecases/login"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/usecases/registrations"
)

// Injectors from wire.go:

func getUsersAuthController() *controller.Controller {
	repository := inmemory_users_storage.New()
	usersRegistrar := registrations.NewUsersRegistrar(repository)
	inmemory_tokens_storageRepository := inmemory_tokens_storage.New()
	usersLoginManager := login.NewUsersLoginManager(repository, inmemory_tokens_storageRepository)
	controllerController := controller.New(usersRegistrar, usersLoginManager)
	return controllerController
}
