// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/raphoester/ddd-library/internal/contexts/authentication/domain/usecases/authenticator"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/domain/usecases/registrar"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/infrastructure/adapters/inmemory_tokens_storage"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/infrastructure/adapters/inmemory_users_storage"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/infrastructure/controller"
)

// Injectors from wire.go:

func getUsersAuthController() *controller.Controller {
	repository := inmemory_users_storage.New()
	registrarRegistrar := registrar.New(repository)
	inmemory_tokens_storageRepository := inmemory_tokens_storage.New()
	usersAuthenticator := authenticator.New(repository, inmemory_tokens_storageRepository)
	controllerController := controller.New(registrarRegistrar, usersAuthenticator)
	return controllerController
}
