// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/raphoester/ddd-library/internal/contexts/authentication/adapters/inmemory_users_storage"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/infrastructure/controllers/registration_controllers"
	"github.com/raphoester/ddd-library/internal/contexts/authentication/usecases/registrations"
)

// Injectors from wire.go:

func getUsersAuthController() *registration_controllers.UsersController {
	repository := inmemory_users_storage.New()
	usersRegistrar := registrations.NewUsersRegistrar(repository)
	usersController := registration_controllers.New(usersRegistrar)
	return usersController
}
